version: "3"

tasks:
  build:
    cmds:
      - npm run build

  test:
    cmds:
      - npm test

  lint:
    cmds:
      - npm run lint

  deployment:package:
    deps: [build]
    cmds:
      - scripts/deployment/package-feature.sh

  deployment:qualification:
    deps: [build]
    cmds:
      - scripts/deployment/qualify-feature.sh
